project:
  type: website

website:
  title: "Laus Wullum"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blogfront.qmd
    right:
      - icon: github
        href: https://github.com/lauswullum
format:
  html:
    theme: lux
    css: styles.css



